steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [ "./gradlew", "jib", "--image=gcr.io/coo-ee/app" ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [ "gcloud", "run", "deploy", "app", "--image=gcr.io/coo-ee/app", "--region=europe-west4" ]
