service: cooee-stream
runtime: java
env: flex
runtime_config:
  jdk: openjdk8
manual_scaling:
  instances: 1
instance_class: B1
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp"
handlers:
  - url: /.*
    script: this field is required, but ignored
network:
  session_affinity: true
