service: cooee-stream
runtime: java
env: flex
runtime_config:
  jdk: openjdk8
resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10
automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_concurrent_requests: 100
instance_class: F2
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp"
handlers:
  - url: /.*
    script: this field is required, but ignored
network:
  session_affinity: true
liveness_check:
  path: "/actuator/health"
readiness_check:
  path: "/actuator/health"
