// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api.proto
package com.baulsupp.cooee.p

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import com.squareup.wire.internal.checkElementsNotNull
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.collections.List
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class CommandRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  @JvmField
  val command: String? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED
  )
  @JvmField
  val parsed_command: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<CommandRequest, CommandRequest.Builder>(ADAPTER, unknownFields) {
  override fun newBuilder(): Builder {
    val builder = Builder()
    builder.command = command
    builder.parsed_command = parsed_command
    builder.addUnknownFields(unknownFields)
    return builder
  }

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is CommandRequest) return false
    return unknownFields == other.unknownFields
        && command == other.command
        && parsed_command == other.parsed_command
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + command.hashCode()
      result = result * 37 + parsed_command.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (command != null) result += """command=${sanitize(command)}"""
    if (parsed_command.isNotEmpty()) result += """parsed_command=${sanitize(parsed_command)}"""
    return result.joinToString(prefix = "CommandRequest{", separator = ", ", postfix = "}")
  }

  fun copy(
    command: String? = this.command,
    parsed_command: List<String> = this.parsed_command,
    unknownFields: ByteString = this.unknownFields
  ): CommandRequest = CommandRequest(command, parsed_command, unknownFields)

  class Builder : Message.Builder<CommandRequest, Builder>() {
    @JvmField
    var command: String? = null

    @JvmField
    var parsed_command: List<String> = emptyList()

    fun command(command: String?): Builder {
      this.command = command
      return this
    }

    fun parsed_command(parsed_command: List<String>): Builder {
      checkElementsNotNull(parsed_command)
      this.parsed_command = parsed_command
      return this
    }

    override fun build(): CommandRequest = CommandRequest(
      command = command,
      parsed_command = parsed_command,
      unknownFields = buildUnknownFields()
    )
  }

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<CommandRequest> = object : ProtoAdapter<CommandRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      CommandRequest::class, 
      "type.googleapis.com/com.baulsupp.cooee.p.CommandRequest"
    ) {
      override fun encodedSize(value: CommandRequest): Int = 
        ProtoAdapter.STRING.encodedSizeWithTag(1, value.command) +
        ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(2, value.parsed_command) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: CommandRequest) {
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.command)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.parsed_command)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): CommandRequest {
        var command: String? = null
        val parsed_command = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> command = ProtoAdapter.STRING.decode(reader)
            2 -> parsed_command.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return CommandRequest(
          command = command,
          parsed_command = parsed_command,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: CommandRequest): CommandRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
