// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baulsupp.cooee.p.CompletionRequest in api.proto
package com.baulsupp.cooee.p

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

public class CompletionRequest(
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  @JvmField
  public val line: String = "",
  unknownFields: ByteString = ByteString.EMPTY
) : Message<CompletionRequest, CompletionRequest.Builder>(ADAPTER, unknownFields) {
  public override fun newBuilder(): Builder {
    val builder = Builder()
    builder.line = line
    builder.addUnknownFields(unknownFields)
    return builder
  }

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is CompletionRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (line != other.line) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (line?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    result += """line=${sanitize(line)}"""
    return result.joinToString(prefix = "CompletionRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(line: String = this.line, unknownFields: ByteString = this.unknownFields):
      CompletionRequest = CompletionRequest(line, unknownFields)

  public class Builder : Message.Builder<CompletionRequest, Builder>() {
    @JvmField
    public var line: String = ""

    public fun line(line: String): Builder {
      this.line = line
      return this
    }

    public override fun build(): CompletionRequest = CompletionRequest(
      line = line,
      unknownFields = buildUnknownFields()
    )
  }

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<CompletionRequest> = object : ProtoAdapter<CompletionRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      CompletionRequest::class, 
      "type.googleapis.com/com.baulsupp.cooee.p.CompletionRequest", 
      PROTO_3, 
      null
    ) {
      public override fun encodedSize(`value`: CompletionRequest): Int {
        var size = value.unknownFields.size
        if (value.line != "") size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.line)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: CompletionRequest): Unit {
        if (value.line != "") ProtoAdapter.STRING.encodeWithTag(writer, 2, value.line)
        writer.writeBytes(value.unknownFields)
      }

      public override fun decode(reader: ProtoReader): CompletionRequest {
        var line: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            2 -> line = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return CompletionRequest(
          line = line,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: CompletionRequest): CompletionRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
