// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api.proto
package com.baulsupp.cooee.p

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class CompletionSuggestion(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  @JvmField
  val word: String? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  @JvmField
  val line: String? = null,
  @field:WireField(
    tag = 3,
    adapter = "com.baulsupp.cooee.p.CommandSuggestion#ADAPTER"
  )
  @JvmField
  val command: CommandSuggestion? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<CompletionSuggestion, CompletionSuggestion.Builder>(ADAPTER, unknownFields) {
  override fun newBuilder(): Builder {
    val builder = Builder()
    builder.word = word
    builder.line = line
    builder.command = command
    builder.addUnknownFields(unknownFields)
    return builder
  }

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is CompletionSuggestion) return false
    return unknownFields == other.unknownFields
        && word == other.word
        && line == other.line
        && command == other.command
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + word.hashCode()
      result = result * 37 + line.hashCode()
      result = result * 37 + command.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (word != null) result += """word=${sanitize(word)}"""
    if (line != null) result += """line=${sanitize(line)}"""
    if (command != null) result += """command=$command"""
    return result.joinToString(prefix = "CompletionSuggestion{", separator = ", ", postfix = "}")
  }

  fun copy(
    word: String? = this.word,
    line: String? = this.line,
    command: CommandSuggestion? = this.command,
    unknownFields: ByteString = this.unknownFields
  ): CompletionSuggestion = CompletionSuggestion(word, line, command, unknownFields)

  class Builder : Message.Builder<CompletionSuggestion, Builder>() {
    @JvmField
    var word: String? = null

    @JvmField
    var line: String? = null

    @JvmField
    var command: CommandSuggestion? = null

    fun word(word: String?): Builder {
      this.word = word
      return this
    }

    fun line(line: String?): Builder {
      this.line = line
      return this
    }

    fun command(command: CommandSuggestion?): Builder {
      this.command = command
      return this
    }

    override fun build(): CompletionSuggestion = CompletionSuggestion(
      word = word,
      line = line,
      command = command,
      unknownFields = buildUnknownFields()
    )
  }

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<CompletionSuggestion> = object : ProtoAdapter<CompletionSuggestion>(
      FieldEncoding.LENGTH_DELIMITED, 
      CompletionSuggestion::class, 
      "type.googleapis.com/com.baulsupp.cooee.p.CompletionSuggestion"
    ) {
      override fun encodedSize(value: CompletionSuggestion): Int = 
        ProtoAdapter.STRING.encodedSizeWithTag(1, value.word) +
        ProtoAdapter.STRING.encodedSizeWithTag(2, value.line) +
        CommandSuggestion.ADAPTER.encodedSizeWithTag(3, value.command) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: CompletionSuggestion) {
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.word)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.line)
        CommandSuggestion.ADAPTER.encodeWithTag(writer, 3, value.command)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): CompletionSuggestion {
        var word: String? = null
        var line: String? = null
        var command: CommandSuggestion? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> word = ProtoAdapter.STRING.decode(reader)
            2 -> line = ProtoAdapter.STRING.decode(reader)
            3 -> command = CommandSuggestion.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return CompletionSuggestion(
          word = word,
          line = line,
          command = command,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: CompletionSuggestion): CompletionSuggestion = value.copy(
        command = value.command?.let(CommandSuggestion.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
