// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baulsupp.cooee.p.ImageUrl in api.proto
package com.baulsupp.cooee.p

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class ImageUrl(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  @JvmField
  val url: String = "",
  unknownFields: ByteString = ByteString.EMPTY
) : Message<ImageUrl, ImageUrl.Builder>(ADAPTER, unknownFields) {
  override fun newBuilder(): Builder {
    val builder = Builder()
    builder.url = url
    builder.addUnknownFields(unknownFields)
    return builder
  }

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ImageUrl) return false
    if (unknownFields != other.unknownFields) return false
    if (url != other.url) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + url.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """url=${sanitize(url)}"""
    return result.joinToString(prefix = "ImageUrl{", separator = ", ", postfix = "}")
  }

  fun copy(url: String = this.url, unknownFields: ByteString = this.unknownFields): ImageUrl =
      ImageUrl(url, unknownFields)

  class Builder : Message.Builder<ImageUrl, Builder>() {
    @JvmField
    var url: String = ""

    fun url(url: String): Builder {
      this.url = url
      return this
    }

    override fun build(): ImageUrl = ImageUrl(
      url = url,
      unknownFields = buildUnknownFields()
    )
  }

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<ImageUrl> = object : ProtoAdapter<ImageUrl>(
      FieldEncoding.LENGTH_DELIMITED, 
      ImageUrl::class, 
      "type.googleapis.com/com.baulsupp.cooee.p.ImageUrl", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: ImageUrl): Int {
        var size = value.unknownFields.size
        if (value.url != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.url)
        return size
      }

      override fun encode(writer: ProtoWriter, value: ImageUrl) {
        if (value.url != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.url)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): ImageUrl {
        var url: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> url = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ImageUrl(
          url = url,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: ImageUrl): ImageUrl = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
