// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baulsupp.cooee.p.LogSeverity in api.proto
package com.baulsupp.cooee.p

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import kotlin.Int
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic

public enum class LogSeverity(
  public override val value: Int
) : WireEnum {
  FATAL(0),
  SEVERE(1),
  INFO(2),
  WARN(3),
  TRACE(4),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<LogSeverity> = object : EnumAdapter<LogSeverity>(
      LogSeverity::class, 
      PROTO_3, 
      LogSeverity.FATAL
    ) {
      public override fun fromValue(value: Int): LogSeverity? = LogSeverity.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(value: Int): LogSeverity? = when (value) {
      0 -> FATAL
      1 -> SEVERE
      2 -> INFO
      3 -> WARN
      4 -> TRACE
      else -> null
    }
  }
}
