// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api.proto
package com.baulsupp.cooee.p

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.WireEnum
import kotlin.Int
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic

enum class LogSeverity(
  override val value: Int
) : WireEnum {
  FATAL(0),

  SEVERE(1),

  INFO(2),

  WARN(3),

  TRACE(4);

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<LogSeverity> = object : EnumAdapter<LogSeverity>(
      LogSeverity::class
    ) {
      override fun fromValue(value: Int): LogSeverity? = LogSeverity.fromValue(value)
    }

    @JvmStatic
    fun fromValue(value: Int): LogSeverity? = when (value) {
      0 -> FATAL
      1 -> SEVERE
      2 -> INFO
      3 -> WARN
      4 -> TRACE
      else -> null
    }
  }
}
