// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baulsupp.cooee.p.RegisterServerRequest in api.proto
package com.baulsupp.cooee.p

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.checkElementsNotNull
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.Unit
import kotlin.collections.List
import kotlin.jvm.JvmField
import okio.ByteString

public class RegisterServerRequest(
  commands: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<RegisterServerRequest, RegisterServerRequest.Builder>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED
  )
  @JvmField
  public val commands: List<String> = immutableCopyOf("commands", commands)

  public override fun newBuilder(): Builder {
    val builder = Builder()
    builder.commands = commands
    builder.addUnknownFields(unknownFields)
    return builder
  }

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is RegisterServerRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (commands != other.commands) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + commands.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    if (commands.isNotEmpty()) result += """commands=${sanitize(commands)}"""
    return result.joinToString(prefix = "RegisterServerRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(commands: List<String> = this.commands, unknownFields: ByteString =
      this.unknownFields): RegisterServerRequest = RegisterServerRequest(commands, unknownFields)

  public class Builder : Message.Builder<RegisterServerRequest, Builder>() {
    @JvmField
    public var commands: List<String> = emptyList()

    public fun commands(commands: List<String>): Builder {
      checkElementsNotNull(commands)
      this.commands = commands
      return this
    }

    public override fun build(): RegisterServerRequest = RegisterServerRequest(
      commands = commands,
      unknownFields = buildUnknownFields()
    )
  }

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<RegisterServerRequest> = object :
        ProtoAdapter<RegisterServerRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      RegisterServerRequest::class, 
      "type.googleapis.com/com.baulsupp.cooee.p.RegisterServerRequest", 
      PROTO_3, 
      null
    ) {
      public override fun encodedSize(value: RegisterServerRequest): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(1, value.commands)
        return size
      }

      public override fun encode(writer: ProtoWriter, value: RegisterServerRequest): Unit {
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 1, value.commands)
        writer.writeBytes(value.unknownFields)
      }

      public override fun decode(reader: ProtoReader): RegisterServerRequest {
        val commands = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> commands.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return RegisterServerRequest(
          commands = commands,
          unknownFields = unknownFields
        )
      }

      public override fun redact(value: RegisterServerRequest): RegisterServerRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
