// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baulsupp.cooee.p.ResponseType in api.proto
package com.baulsupp.cooee.p

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import kotlin.Int
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic

public enum class ResponseType(
  public override val value: Int
) : WireEnum {
  DEFAULT_RESPONSE(0),
  REQUEST_RESPONSE(1),
  STREAM_RESPONSE(2),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ResponseType> = object : EnumAdapter<ResponseType>(
      ResponseType::class, 
      PROTO_3, 
      ResponseType.DEFAULT_RESPONSE
    ) {
      public override fun fromValue(value: Int): ResponseType? = ResponseType.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(value: Int): ResponseType? = when (value) {
      0 -> DEFAULT_RESPONSE
      1 -> REQUEST_RESPONSE
      2 -> STREAM_RESPONSE
      else -> null
    }
  }
}
