// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baulsupp.cooee.p.TableColumn in api.proto
package com.baulsupp.cooee.p

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.checkElementsNotNull
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.Unit
import kotlin.collections.List
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

public class TableColumn(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  @JvmField
  public val name: String = "",
  values: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<TableColumn, TableColumn.Builder>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED
  )
  @JvmField
  public val values: List<String> = immutableCopyOf("values", values)

  public override fun newBuilder(): Builder {
    val builder = Builder()
    builder.name = name
    builder.values = values
    builder.addUnknownFields(unknownFields)
    return builder
  }

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is TableColumn) return false
    if (unknownFields != other.unknownFields) return false
    if (name != other.name) return false
    if (values != other.values) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + name.hashCode()
      result = result * 37 + values.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    result += """name=${sanitize(name)}"""
    if (values.isNotEmpty()) result += """values=${sanitize(values)}"""
    return result.joinToString(prefix = "TableColumn{", separator = ", ", postfix = "}")
  }

  public fun copy(
    name: String = this.name,
    values: List<String> = this.values,
    unknownFields: ByteString = this.unknownFields
  ): TableColumn = TableColumn(name, values, unknownFields)

  public class Builder : Message.Builder<TableColumn, Builder>() {
    @JvmField
    public var name: String = ""

    @JvmField
    public var values: List<String> = emptyList()

    public fun name(name: String): Builder {
      this.name = name
      return this
    }

    public fun values(values: List<String>): Builder {
      checkElementsNotNull(values)
      this.values = values
      return this
    }

    public override fun build(): TableColumn = TableColumn(
      name = name,
      values = values,
      unknownFields = buildUnknownFields()
    )
  }

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<TableColumn> = object : ProtoAdapter<TableColumn>(
      FieldEncoding.LENGTH_DELIMITED, 
      TableColumn::class, 
      "type.googleapis.com/com.baulsupp.cooee.p.TableColumn", 
      PROTO_3, 
      null
    ) {
      public override fun encodedSize(value: TableColumn): Int {
        var size = value.unknownFields.size
        if (value.name != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.name)
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(2, value.values)
        return size
      }

      public override fun encode(writer: ProtoWriter, value: TableColumn): Unit {
        if (value.name != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.values)
        writer.writeBytes(value.unknownFields)
      }

      public override fun decode(reader: ProtoReader): TableColumn {
        var name: String = ""
        val values = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> name = ProtoAdapter.STRING.decode(reader)
            2 -> values.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return TableColumn(
          name = name,
          values = values,
          unknownFields = unknownFields
        )
      }

      public override fun redact(value: TableColumn): TableColumn = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
