// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: api.proto
package com.baulsupp.cooee.p

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.jvm.JvmField
import okio.ByteString

class TodoRequest(
  unknownFields: ByteString = ByteString.EMPTY
) : Message<TodoRequest, TodoRequest.Builder>(ADAPTER, unknownFields) {
  override fun newBuilder(): Builder {
    val builder = Builder()
    builder.addUnknownFields(unknownFields)
    return builder
  }

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is TodoRequest) return false
    return unknownFields == other.unknownFields
  }

  override fun hashCode(): Int = unknownFields.hashCode()

  override fun toString(): String = "TodoRequest{}"

  fun copy(unknownFields: ByteString = this.unknownFields): TodoRequest = TodoRequest(unknownFields)

  class Builder : Message.Builder<TodoRequest, Builder>() {
    override fun build(): TodoRequest = TodoRequest(
      unknownFields = buildUnknownFields()
    )
  }

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<TodoRequest> = object : ProtoAdapter<TodoRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      TodoRequest::class, 
      "type.googleapis.com/com.baulsupp.cooee.p.TodoRequest"
    ) {
      override fun encodedSize(value: TodoRequest): Int = 
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: TodoRequest) {
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): TodoRequest {
        val unknownFields = reader.forEachTag(reader::readUnknownField)
        return TodoRequest(
          unknownFields = unknownFields
        )
      }

      override fun redact(value: TodoRequest): TodoRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
